services:
  db:
    image: mariadb:11.4
    container_name: taskmaster-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: taskmaster
      MYSQL_USER: taskmaster_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    ports:
      - "3306:3306"
    volumes:
      - "./db_data:/var/lib/mysql"
    secrets:
      - db_root_password
      - db_user_password

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt
