FROM openjdk:21-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY mvnw .
COPY mvnw.cmd .
COPY .mvn .mvn

COPY pom.xml .
RUN ./mvnw dependency:go-offline -B

VOLUME ["/app/src"]

EXPOSE 8080 5005

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
