spring:
  datasource:
    url: jdbc:mariadb://db:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD}
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

logging:
  level:
    org.selfstudy.taskmaster: DEBUG
    org.hibernate.SQL: DEBUG
